# Generated by Django 5.2.11 on 2026-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quiz_and_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source_page',
            field=models.CharField(blank=True, help_text='Page path where the lead submitted (e.g. /, /about)', max_length=500),
        ),
    ]
