# Generated by Django 5.2.11 on 2026-02-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_create_hr_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('job_type', models.CharField(default='FULL TIME', max_length=50)),
                ('work_mode', models.CharField(default='WORK FROM OFFICE', max_length=50)),
                ('positions', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(default='', max_length=255)),
                ('about_us', models.TextField(blank=True)),
                ('role_overview', models.TextField(blank=True)),
                ('responsibilities', models.JSONField(blank=True, default=list, help_text='List of {"title": "...", "description": "..."}')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from careers page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
