# Generated by Django 5.2.1 on 2026-02-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_lead_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='utm_params',
            field=models.JSONField(blank=True, default=dict, help_text='UTM parameters from URL (utm_source, utm_medium, utm_campaign, etc.)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_params',
            field=models.JSONField(blank=True, default=dict, help_text='UTM parameters from URL (utm_source, utm_medium, utm_campaign, etc.)'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='utm_params',
            field=models.JSONField(blank=True, default=dict, help_text='UTM parameters from URL (utm_source, utm_medium, utm_campaign, etc.)'),
        ),
    ]
