# Generated by Django 5.2.1 on 2026-02-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_utm_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='utm_source',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='utm_source',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
