# Generated by Django 5.2.1 on 2026-02-17 12:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_utm_source_medium_campaign_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIDEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('published_date', models.DateField(help_text='Date shown on the episode card (e.g. January 25, 2026)')),
                ('youtube_url', models.URLField(help_text='Full YouTube watch URL (e.g. https://www.youtube.com/watch?v=...)', max_length=500)),
                ('thumbnail', models.ImageField(help_text='Image for the big left episode card', upload_to=api.models.bid_episode_thumbnail_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BID Episode',
                'verbose_name_plural': 'BID Episodes',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
