# Generated by Django 5.2.1 on 2026-03-21 06:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_bid_episode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for cards / SEO')),
                ('date_display', models.CharField(blank=True, help_text='Display date e.g. MARCH 18, 2026 (shown on cards)', max_length=80)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of strings e.g. ["Career", "Interview"]')),
                ('content_json', models.JSONField(blank=True, default=dict, help_text='Tiptap JSON document')),
                ('cover_image', models.ImageField(blank=True, help_text='Thumbnail for listing / featured card', null=True, upload_to=api.models.marketing_blog_cover_path)),
                ('hide_from_resources', models.BooleanField(default=False, help_text='If true, hide from /resources grid (still open via direct URL)')),
                ('featured_on_resources', models.BooleanField(default=False, help_text='Show as the wide featured card on /resources (only one recommended)')),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=300)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketing blog',
                'verbose_name_plural': 'Marketing blogs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingBlogUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=api.models.marketing_blog_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
