# Generated by Django 5.2.1 on 2026-04-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_jobapplication_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enquiry / query text from the form (also sent to CRM as cf_remarks).'),
        ),
    ]
