# Generated by Django 5.2.1 on 2026-06-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_lead_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerittoOutboundAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, choices=[('submit_lead', 'Submit lead'), ('quiz_submit', 'Quiz submit'), ('backfill', 'Backfill')], max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_mobile', models.CharField(blank=True, max_length=20)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('http_method', models.CharField(default='POST', max_length=10)),
                ('request_headers', models.JSONField(blank=True, default=dict, help_text='Sanitized (secrets redacted).')),
                ('request_body', models.JSONField(blank=True, default=dict, help_text='Sanitized (secrets redacted).')),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meritto outbound API log',
                'verbose_name_plural': 'Meritto outbound API logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
