# Generated by Django 5.2.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_meritto_outbound_api_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must match CRM / lead program name (e.g. Aviva Nirmaan Program - Direct Sales Executive)', max_length=255, unique=True)),
                ('details', models.CharField(blank=True, help_text='Result card line, e.g. CTC of upto Rs 3.5 LPA', max_length=500)),
                ('duration', models.CharField(blank=True, help_text='Result card line, e.g. 2-month program', max_length=200)),
                ('link', models.CharField(blank=True, help_text='Microsite URL opened from Explore Program', max_length=500)),
                ('fee', models.PositiveIntegerField(default=0, help_text='Tie-break when two programs have the same quiz score (higher fee wins)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from marketing dropdowns (existing mappings stay)')),
                ('is_fallback', models.BooleanField(default=False, help_text='Used when the quiz cannot pick a winner. Only one program should be checked.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quiz program',
                'verbose_name_plural': 'Quiz programs',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Display order (1 = first question). Must be unique.', unique=True)),
                ('question', models.TextField()),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this question from the live quiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quiz question',
                'verbose_name_plural': 'Quiz questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('text', models.CharField(max_length=500)),
                ('program_1', models.ForeignKey(blank=True, help_text='First program that receives +1 when this option is selected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_as_first', to='api.quizprogram')),
                ('program_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_as_second', to='api.quizprogram')),
                ('program_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_as_third', to='api.quizprogram')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.quizquestion')),
            ],
            options={
                'verbose_name': 'Quiz option',
                'verbose_name_plural': 'Quiz options',
                'ordering': ['mapping'],
                'unique_together': {('question', 'mapping')},
            },
        ),
    ]
