# Generated by Django 5.2.1

from django.db import migrations, models
import api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_banking_sales_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('linkedin', 'LinkedIn post'), ('google', 'Google review')], default='linkedin', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('headline', models.CharField(blank=True, help_text='Role line under the name, e.g. Digital Marketer | Programmatic Advertising', max_length=300)),
                ('body', models.TextField(help_text='Review or post text')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Star rating for Google reviews (1–5)')),
                ('time_label', models.CharField(blank=True, help_text='LinkedIn time line, e.g. 1y • Edited', max_length=80)),
                ('connection_label', models.CharField(blank=True, default='3rd', help_text='LinkedIn connection degree, e.g. 3rd', max_length=20)),
                ('hashtags', models.CharField(blank=True, help_text='Space-separated tags, e.g. #NewBeginnings #Gratitude', max_length=400)),
                ('source_url', models.URLField(blank=True, help_text='LinkedIn post URL or Google review URL', max_length=500)),
                ('profile_image', models.ImageField(blank=True, help_text='Avatar. If empty, the first letter of the name is shown.', null=True, upload_to=api.models.testimonial_image_path)),
                ('post_image', models.ImageField(blank=True, help_text='Optional photo inside a LinkedIn-style post', null=True, upload_to=api.models.testimonial_image_path)),
                ('is_published', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
