# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_site_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetestimonial',
            name='name',
            field=models.CharField(blank=True, help_text='Shown on Google reviews. Leave blank for a LinkedIn embed.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitetestimonial',
            name='body',
            field=models.TextField(blank=True, help_text='Review text. Leave blank for a LinkedIn embed.'),
        ),
        migrations.AlterField(
            model_name='sitetestimonial',
            name='source_url',
            field=models.URLField(blank=True, help_text='LinkedIn post URL (embedded on the page) or Google review URL', max_length=500),
        ),
    ]
